Ecommerce/Models/Cart.cs
using System.ComponentModel.DataAnnotations;

namespace Ecommerce.Models
{
    public class Cart
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string UserId { get; set; }

        [Required]
        public int ProductId { get; set; }

        public Product Product { get; set; }
        
        public int Quantity { get; set; }
    }
}

Ecommerce/Controllers/CheckoutController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Data;
using Ecommerce.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace Ecommerce.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CheckoutController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }


        // GET: Checkout/Create
        public async Task<IActionResult> Address()
        {
            var user = await _userManager.GetUserAsync(User);

            var address = await _context.Address.SingleOrDefaultAsync(e => e.UserId == user.Id);

            if (address!= null)
            {
                var id = address.Id;

                ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
                ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
                ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");

                return RedirectToAction("Edit",new {id});
            }

            ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
            ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Checkout/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Address(
        [Bind(
            "Id,FirstName,LastName,MobileNo,Email,Company,Street,Number,Gender,Pincode,ShppingAddress,State,City,Country,UserId"
        )] Address address)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                address.UserId = user.Id;
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction("PaymentType");
            }
            ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
            ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View("PaymentType");
        }

        // GET: Checkout/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address.SingleOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }
            ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
            ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View(address);
        }

        // POST: Checkout/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
        [Bind(
            "Id,FirstName,LastName,MobileNo,Email,Company,Street,Number,Gender,Pincode,ShppingAddress,State,City,Country,UserId"
        )] Address address)
        {
            if (id != address.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(User);
                    address.UserId = user.Id;
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("PaymentType");
            }
            ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
            ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View(address);
        }

        [HttpGet]
        public IActionResult PaymentType()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PaymentType([Bind("Id,Type,Allowed")] Payment payment)
        {
            if (!ModelState.IsValid) return View("Index");

            payment = new Payment()
            {
                Type = payment.Type
            };

            HttpContext.Session.SetString("PaymentType", $"{payment.Type}");

            return RedirectToAction("OrderOverview");
        }


        private bool AddressExists(int id)
        {
            return _context.Address.Any(e => e.Id == id);
        }

        [HttpGet]
        public async Task<IActionResult> OrderOverview()
        {
            var userId = _userManager.GetUserId(User);

            var carts = from c in _context.Carts
                        where c.UserId == userId
                        select c;

            var applicationDbContext = carts.Include(c => c.Product);

            return View(await applicationDbContext.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> OrderOverview(Order order)
        {
            if (order == null) throw new ArgumentNullException(nameof(order));

            var user = await _userManager.GetUserAsync(User);

            ViewBag.PaymetnType = HttpContext.Session.GetString("PaymentType");

            var payment = new Payment()
            {
                Type = HttpContext.Session.GetString("PaymentType")
            };

            HttpContext.Session.Clear();

            order = new Order()
            {
                Payment = payment,
                Shipper = new Shipper(),
                Date = DateTime.Now.ToString(CultureInfo.InvariantCulture),
                Number = RandomNumberGenerator.Create().GetHashCode(),
                UserId = user.Id,
                TimeStamp = DateTime.Now,
                Paid = false,
            };


            var carts = await (from c in _context.Carts
                               where c.UserId == user.Id
                               select c).ToListAsync();


            foreach (var cart in carts)
            {
                var orderDetail = new OrderDetail()
                {
                    ProductId = cart.ProductId,
                    Order = order,
                    BillDate = DateTime.Now.ToString(CultureInfo.InvariantCulture),
                    OrderNumber = RandomNumberGenerator.Create().GetHashCode(),
                    ShipDate = new DateTime().AddDays(7).ToString(CultureInfo.InvariantCulture),
                };
                _context.Add(orderDetail);
            }


            foreach (var cart in carts)
            {
                _context.Remove(cart);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "home");
        }
    }
}

Ecommerce/Controllers/ProductsController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Data;
using Ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce.Controllers
{
	[Authorize]
	public class ProductsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly IHostingEnvironment _hostingEnvironment;
		private readonly UserManager<ApplicationUser> _userManager;

		public ProductsController(ApplicationDbContext context, 
			UserManager<ApplicationUser> userManager,
			IHostingEnvironment hostingEnvironment)
		{
			_hostingEnvironment = hostingEnvironment;
			_userManager = userManager;
			_context = context;
		}

		// GET: Products
		[AllowAnonymous]
		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.Products.Include(p => p.ApplicationUser).Include(p => p.Category);
			return View(await applicationDbContext.ToListAsync());
		}

		// GET: Products/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
				return NotFound();

			var product = await _context.Products
				.Include(p => p.ApplicationUser)
				.Include(p => p.Category)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (product == null)
				return NotFound();

			return View(product);
		}

		// GET: Products/Create
		public IActionResult Create()
		{
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
			return View();
		}

		// POST: Products/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(
		[Bind(
			"Id,Name,Description,QuantityPerUnit,UnitPrice,AvailabelSize,Size,Color,Dicount,UnitWeight,UnitsInStock,DiscountAvailabel,Picture,Note,UserId,CategoryId"
		)] Product product, IFormFile Picture)
		{
			var currntUser = await _userManager.GetUserAsync(User);

			if (Picture != null)
			{
				var uploadPath = Path.Combine(_hostingEnvironment.WebRootPath, "products");

				Directory.CreateDirectory(Path.Combine(uploadPath, $"{currntUser.Id}{product.Name}"));

				var fileName = Path.GetFileName(Picture.FileName);

				using (
					var fileStream = new FileStream(
						Path.Combine(uploadPath, $"{currntUser.Id}{product.Name}", fileName), FileMode.Create))
				{
					await Picture.CopyToAsync(fileStream);
				}
				product.Picture = $"{currntUser.Id}{product.Name}/{fileName}";
				product.UserId = currntUser.Id;
			}

			if (ModelState.IsValid)
			{
				_context.Add(product);
				await _context.SaveChangesAsync();
				return RedirectToAction("Index");
			}
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", product.UserId);
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
			return View(product);
		}


		// GET: Products/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
				return NotFound();

			var product = await _context.Products.SingleOrDefaultAsync(m => m.Id == id);
			if (product == null)
				return NotFound();
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", product.UserId);
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
			return View(product);
		}

		// POST: Products/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id,
		[Bind(
			"Id,Name,Description,QuantityPerUnit,UnitPrice,AvailabelSize,Size,Color,Dicount,UnitWeight,UnitsInStock,DiscountAvailabel,Picture,Note,UserId,CategoryId"
		)] Product product)
		{
			if (id != product.Id)
				return NotFound();

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(product);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ProductExists(product.Id))
						return NotFound();
					throw;
				}
				return RedirectToAction("Index");
			}
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", product.UserId);
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
			return View(product);
		}

		// GET: Products/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
				return NotFound();

			var product = await _context.Products
				.Include(p => p.ApplicationUser)
				.Include(p => p.Category)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (product == null)
				return NotFound();

			return View(product);
		}

		// POST: Products/Delete/5
		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var product = await _context.Products.SingleOrDefaultAsync(m => m.Id == id);
			_context.Products.Remove(product);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		private bool ProductExists(int id)
		{
			return _context.Products.Any(e => e.Id == id);
		}
	}
}

Ecommerce/Views/Carts/Delete.cshtml
@model Cart

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr/>
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id"/>
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default"/> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Ecommerce/Views/Carts/Details.cshtml
@model Cart

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Cart</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Ecommerce/Views/Carts/Edit.cshtml
@model Cart

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Cart</h4>
        <hr/>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id"/>
        <div class="form-group">
            <label asp-for="UserId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="UserId" class="form-control"/>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Quantity" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Quantity" class="form-control"/>
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Ecommerce/Views/Carts/Index.cshtml
@model IEnumerable<Cart>

@{
    ViewData["Title"] = "Shopping Cart";
}
<br/>
@if (TempData["cartExist"] != null)
{
    <div class="alert alert-info">
         <strong>Info!</strong> @TempData["cartExist"]
     </div>
}

<h1>Cart @Html.ViewData["carts"]</h1>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product.Picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.UnitPrice)
        </th>
        <th>
            SubTotal
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @{
        decimal totalPrice = 0;
    }
    @foreach (var item in Model)
    {
        var subtotal = item.Product.UnitPrice * item.Quantity;
        totalPrice = totalPrice + subtotal;

        <tr>
            <td>
                <img class="img-thumbnail" src="~/products/@Html.DisplayFor(modelItem => item.Product.Picture)" alt="@Html.DisplayFor(modelItem => item.Product.Name)"/>
            </td>
            <td>
                <input class="input-sm" value="@Html.DisplayFor(modelItem => item.Quantity)"/>
            </td>
            <td>
                $@Html.DisplayFor(modelitem => item.Product.UnitPrice)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => subtotal)
            </td>
            <td>
                <a asp-action="Details" asp-controller="Products" asp-route-id="@item.Product.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
    <tr>
        <td>
            @if (totalPrice == 0)
            {
                <h1>Your cart is currently empty</h1>
                <a class="btn btn-primary" asp-action="Index" asp-controller="Home">Srat Shoping</a>
            }
            else
            {
                <td colspan="2">
                    <h2> Total Price</h2>
                </td>
                <td>
                    <h2>$@totalPrice</h2>
                </td>
                <td>
                    <h2>
                        <a asp-controller="Checkout" asp-action="Address" class="btn btn-primary">Checkout</a>
                    </h2>
                </td>
            }
        </td>

    </tr>
</table>