Ecommerce/Models/Address.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ecommerce.Models
{
    public class Address
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",ErrorMessage = "Entered phone format is not valid.")]
        public string MobileNo { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        public string Company { get; set; }

        [Required]
        public string Street { get; set; }

        [Required]
        public string Number { get; set; }

        [Required]
        public Gender Gender { get; set; }

        [Required]
        [DataType(DataType.PostalCode)]
        [MinLength(3), MaxLength(6)]
        public string Pincode { get; set; }

        [Required]
        [DisplayName("Shipping Address")]
        public string ShppingAddress { get; set; }

        [Required]
        public string State { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public Country  Country { get; set; }

        [Required]
        public string UserId { get; set; }
        [ForeignKey("UserId")]
        public virtual ApplicationUser ApplicationUser { get; set; }


    }

    public enum Country
    {
        India,
        Australia,
        Canada,
        Italy,
        UnitedStates,
        UnitedKingdom,
        China,
        Japan,
        Germany,
        France,
    }
}

Ecommerce/Models/Payment.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Ecommerce.Models
{
    public class Payment
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Type { get; set; }
        public string Allowed { get; set; }

        public ICollection<Order> Orders { get; set; }
    }
}

Ecommerce/Controllers/CartsController.cs
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Data;
using Ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce.Controllers
{
    [Authorize]
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CartsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            var carts = from c in _context.Carts
                where c.UserId == userId
                select c;

            var applicationDbContext = carts.Include(c => c.Product);
            ViewData["carts"] = applicationDbContext.Count();
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var cart = await _context.Carts.Include(c => c.Product).SingleOrDefaultAsync(m => m.ProductId == id);

            if (cart == null)
                return NotFound();

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            return RedirectToAction("Index");
        }

        // POST: Carts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,UserId,ProductId,Quantity")] Cart cart)
        {
            var usre = await _userManager.GetUserAsync(User);

            if (ProductCartExist(cart.ProductId, usre.Id))
            {
                TempData["cartExist"] = "This product alreay in cart";
                return RedirectToAction("Index");
            }

            if (!ModelState.IsValid) return View("Error");

            cart.UserId = usre.Id;

            _context.Add(cart);

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var cart = await _context.Carts.SingleOrDefaultAsync(m => m.ProductId == id);
            if (cart == null)
                return NotFound();
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Description", cart.ProductId);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,ProductId,Quantity")] Cart cart)
        {
            if (id != cart.Product.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                        return NotFound();
                    throw;
                }
                return RedirectToAction("Index");
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Description", cart.ProductId);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var cart = await _context.Carts
                .Include(c => c.Product)
                .SingleOrDefaultAsync(m => m.Product.Id == id);
            if (cart == null)
                return NotFound();

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cart = await _context.Carts.SingleOrDefaultAsync(m => m.ProductId == id);
            _context.Carts.Remove(cart);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool UserExists(string userid)
        {
            return _context.Carts.Any(u => u.UserId == userid);
        }

        private bool CartExists(int id)
        {
            return _context.Carts.Any(e => e.ProductId == id);
        }

        private bool ProductCartExist(int cartid, string usrid)
        {
            if (UserExists(usrid) && CartExists(cartid))
                return true;

            return false;
        }
    }
}

Ecommerce/Controllers/CheckoutController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Data;
using Ecommerce.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace Ecommerce.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CheckoutController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }


        // GET: Checkout/Create
        public async Task<IActionResult> Address()
        {
            var user = await _userManager.GetUserAsync(User);

            var address = await _context.Address.SingleOrDefaultAsync(e => e.UserId == user.Id);

            if (address!= null)
            {
                var id = address.Id;

                ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
                ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
                ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");

                return RedirectToAction("Edit",new {id});
            }

            ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
            ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Checkout/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Address(
        [Bind(
            "Id,FirstName,LastName,MobileNo,Email,Company,Street,Number,Gender,Pincode,ShppingAddress,State,City,Country,UserId"
        )] Address address)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                address.UserId = user.Id;
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction("PaymentType");
            }
            ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
            ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View("PaymentType");
        }

        // GET: Checkout/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address.SingleOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }
            ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
            ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View(address);
        }

        // POST: Checkout/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
        [Bind(
            "Id,FirstName,LastName,MobileNo,Email,Company,Street,Number,Gender,Pincode,ShppingAddress,State,City,Country,UserId"
        )] Address address)
        {
            if (id != address.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(User);
                    address.UserId = user.Id;
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("PaymentType");
            }
            ViewData["Gender"] = new SelectList(Enum.GetNames(typeof(Gender)).ToList());
            ViewData["Country"] = new SelectList(Enum.GetNames(typeof(Country)).ToList());
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View(address);
        }

        [HttpGet]
        public IActionResult PaymentType()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PaymentType([Bind("Id,Type,Allowed")] Payment payment)
        {
            if (!ModelState.IsValid) return View("Index");

            payment = new Payment()
            {
                Type = payment.Type
            };

            HttpContext.Session.SetString("PaymentType", $"{payment.Type}");

            return RedirectToAction("OrderOverview");
        }


        private bool AddressExists(int id)
        {
            return _context.Address.Any(e => e.Id == id);
        }

        [HttpGet]
        public async Task<IActionResult> OrderOverview()
        {
            var userId = _userManager.GetUserId(User);

            var carts = from c in _context.Carts
                        where c.UserId == userId
                        select c;

            var applicationDbContext = carts.Include(c => c.Product);

            return View(await applicationDbContext.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> OrderOverview(Order order)
        {
            if (order == null) throw new ArgumentNullException(nameof(order));

            var user = await _userManager.GetUserAsync(User);

            ViewBag.PaymetnType = HttpContext.Session.GetString("PaymentType");

            var payment = new Payment()
            {
                Type = HttpContext.Session.GetString("PaymentType")
            };

            HttpContext.Session.Clear();

            order = new Order()
            {
                Payment = payment,
                Shipper = new Shipper(),
                Date = DateTime.Now.ToString(CultureInfo.InvariantCulture),
                Number = RandomNumberGenerator.Create().GetHashCode(),
                UserId = user.Id,
                TimeStamp = DateTime.Now,
                Paid = false,
            };


            var carts = await (from c in _context.Carts
                               where c.UserId == user.Id
                               select c).ToListAsync();


            foreach (var cart in carts)
            {
                var orderDetail = new OrderDetail()
                {
                    ProductId = cart.ProductId,
                    Order = order,
                    BillDate = DateTime.Now.ToString(CultureInfo.InvariantCulture),
                    OrderNumber = RandomNumberGenerator.Create().GetHashCode(),
                    ShipDate = new DateTime().AddDays(7).ToString(CultureInfo.InvariantCulture),
                };
                _context.Add(orderDetail);
            }


            foreach (var cart in carts)
            {
                _context.Remove(cart);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "home");
        }
    }
}

Ecommerce/Views/Checkout/Address.cshtml
@model Ecommerce.Models.Address

@{
    ViewData["Title"] = "Create";
}

<br />
<div id="all">
    <div id="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 clearfix" id="checkout">
                        <div class="box">
                            <form asp-action="Address">
                                <ul class="nav nav-pills nav-justified">
                                    <li class="active"><a asp-action="Address"><i class="fa fa-map-marker"></i><br>Address</a></li>
                                    <li class="disabled"><a href="#"><i class="fa fa-money"></i><br>Payment Type</a></li>
                                    <li class="disabled"><a href="#"><i class="fa fa-eye"></i><br>Ordering overview</a></li>
                                </ul>
                                <div class="content">
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <div class="form-group">
                                                <label asp-for="Gender" for="salutation">Hello</label>
                                                <Select asp-for="Gender"  asp-items="ViewBag.Gender" type="text" class="form-control" id="salutation"></Select>
                                                <span asp-validation-for="Gender" class="text-danger"></span>
                                            </div>
                                        </div>
                                       </div>
                                    <!-- /.row -->
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label asp-for="FirstName"></label>
                                                <input asp-for="FirstName" type="text" class="form-control" id="firstname">
                                                <span asp-validation-for="FirstName" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label asp-for="LastName"></label>
                                                <input asp-for="LastName" type="text" class="form-control" id="lastname">
                                                <span asp-validation-for="LastName" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- /.row -->
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label asp-for="Company"></label>
                                                <input asp-for="Company" type="text" class="form-control" id="company">
                                                <span asp-validation-for="Company" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-sm-4">
                                            <div class="form-group">
                                                <label asp-for="Street"></label>
                                                <input asp-for="Street" type="text" class="form-control" id="street">
                                                <span asp-validation-for="Street" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-sm-4">
                                            <div class="form-group">
                                                <label asp-for="State"></label>
                                                <input asp-for="State" type="text" class="form-control" id="street">
                                                <span asp-validation-for="State" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-2">
                                            <div class="form-group">
                                                <label asp-for="Number"></label>
                                                <input asp-for="Number" type="text" class="form-control" id="zip">
                                                <span asp-validation-for="Number" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                    <div class="row">
                                        <div class="col-sm-6 col-md-2">
                                            <div class="form-group">
                                                <label asp-for="Pincode"></label>
                                                <input asp-for="Pincode" type="text" class="form-control" id="zip">
                                                <span asp-validation-for="Pincode" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-4">
                                            <div class="form-group">
                                                <label asp-for="City"></label>
                                                <input asp-for="City" type="text" class="form-control" id="city">
                                                <span asp-validation-for="City" class="text-danger"></span>
                                            </div>
                                        </div>


                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label asp-for="Country"></label>
                                                <select asp-for="Country" class="form-control" id="country" asp-items="ViewBag.Country"></select>
                                                <span asp-validation-for="Country" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label asp-for="MobileNo"></label>
                                                <input asp-for="MobileNo" type="text" class="form-control" id="phone">
                                                <span asp-validation-for="MobileNo" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label asp-for="Email"></label>
                                                <input asp-for="Email" type="text" class="form-control" id="email">
                                                <span asp-validation-for="Email" class="text-danger"></span>
                                            </div>
                                        </div> 
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label asp-for="ShppingAddress"></label>
                                                <input asp-for="ShppingAddress" type="text" class="form-control" id="email">
                                                <span asp-validation-for="ShppingAddress" class="text-danger"></span>
                                            </div>
                                        </div>               
                                        <div class="col-sm-6 hidden">
                                            <div class="form-group">
                                                <label asp-for="UserId"></label>
                                                <input asp-for="UserId" type="text" value="MyId" class="form-control" id="email">
                                                <span asp-validation-for="UserId" class="text-danger"></span>
                                            </div>
                                        </div>                                     
                                    </div>
                                    <!-- /.row -->
                                </div>
                                <div class="box-footer">
                                    <div class="pull-left">
                                        <a asp-action="Index" asp-controller="Carts" class="btn btn-default"><i class="fa fa-chevron-left"></i>Back</a>
                                    </div>
                                    <div class="pull-right">
                                        <input type="submit" value="Continue" class="btn btn-default" />
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.box -->

                    </div>
                    <!-- /.col-md-9 -->

                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->
    </div>
<!-- /#all -->

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Ecommerce/Views/Checkout/Create.cshtml
@model Ecommerce.Models.Address

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Address</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MobileNo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MobileNo" class="form-control" />
                <span asp-validation-for="MobileNo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Company" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Street" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Number" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Gender" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="Gender" class="form-control" asp-items="ViewBag.Gender"></select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Pincode" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Pincode" class="form-control" />
                <span asp-validation-for="Pincode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ShppingAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ShppingAddress" class="form-control" />
                <span asp-validation-for="ShppingAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Country" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="Country" class="form-control" asp-items="ViewBag.Country"></select>
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group hidden">
            <label asp-for="UserId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
</div>